[package]
name = "qr"
version = "0.1.0"
authors = ["Abhyudit Jain"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.12.0"
structopt = "0.3.18"
image = "0.23.10"
log = "0.4.11"
simple_logger = "1.10.0"